# Chapter 04 推測統計の基本 first

これまでは __記述統計__ が中心だったが  
これからは __推測統計__ に入っていく.

In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

%precision 3
%matplotlib inline

/opt/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
df = pd.read_csv('../data/ch4_scores400.csv')
scores = np.array(df['点数'])
scores[:10]

array([76, 55, 80, 80, 74, 61, 81, 76, 23, 80])

## 4.1　|　母集団と標本

推測したい観測対象全体を__母集団__  
推測に使う観測対象の一部分のことを__標本__ という.  

母集団から標本を取り出すことを__標本抽出__  
取り出す標本の数のことを__標本の大きさ__ , __サンプルサイズ__
という.

標本から計算される平均や分布, 相関係数などを  
__標本統計量__,

母集団の平均や分散, 相関係数などを  
__母数__ という.

標本平均で母平均を推測するとき,  
標本平均は母平均の__推定量__であるという.

実際に標本のデータを用いて計算した結果を__推定値__ という.

### 4.1.1　標本の抽出方法

ランダムに標本を抽出する方法を__無作為抽出__という.

複数回同じ標本を選ぶ方法を__復元抽出__  
同じ標本は一度しか選ばない方法を__非復元抽出__  
という.

In [7]:
# 無作為抽出
print(np.random.choice([1, 2, 3, 4, 5], 3))
print(np.random.choice(np.random.randn(10), 3))

[1 2 1]
[0.688 0.688 1.177]


In [8]:
# 非復元抽出
np.random.choice([1, 2, 3, 4, 5], 3, replace=False)

array([4, 5, 3])

In [10]:
# シード値設定
np.random.seed(0)
np.random.choice([1, 2, 3, 4, 5], 3)

array([5, 1, 4])

In [11]:
np.random.seed(0)
sample = np.random.choice(scores, 20)
sample.mean()

70.4

In [12]:
scores.mean()

69.53

In [13]:
for i in range(5):
    sample = np.random.choice(scores, 20)
    print(f'{i + 1} 回目 標本平均', sample.mean())

1 回目 標本平均 72.45
2 回目 標本平均 63.7
3 回目 標本平均 66.05
4 回目 標本平均 71.7
5 回目 標本平均 74.15
